### ISSUE TITLE
BUG..

### ISSUE THREAD

**Issue by Shiba-Matic** [ethereum-boilerplate/ethereum-boilerplate#121]
Line 172:80:   Delete `␍`  prettier/prettier
  Line 173:31:   Delete `␍`  prettier/prettier
  Line 174:22:   Delete `␍`  prettier/prettier
  Line 175:29:   Delete `␍`  prettier/prettier
  Line 176:37:   Delete `␍`  prettier/prettier
  Line 177:41:   Delete `␍`  prettier/prettier
  Line 178:80:   Delete `␍`  prettier/prettier
  Line 179:25:   Delete `␍`  prettier/prettier
  Line 180:22:   Delete `␍`  prettier/prettier
  Line 181:29:   Delete `␍`  prettier/prettier
  Line 182:56:   Delete `␍`  prettier/prettier
  Line 183:21:   Delete `␍`  prettier/prettier
  Line 184:61:   Delete `␍`  prettier/prettier
  Line 185:22:   Delete `␍`  prettier/prettier
  Line 186:29:   Delete `␍`  prettier/prettier
  Line 187:22:   Delete `␍`  prettier/prettier
  Line 188:16:   Delete `␍`  prettier/prettier
  Line 189:14:   Delete `␍`  prettier/prettier
  Line 190:56:   Delete `␍`  prettier/prettier
  Line 191:18:   Delete `␍`  prettier/prettier
  Line 192:15:   Delete `␍`  prettier/prettier
  Line 193:22:   Delete `␍`  prettier/prettier
  Line 194:81:   Delete `␍`  prettier/prettier
  Line 195:16:   Delete `␍`  prettier/prettier
  Line 196:12:   Delete `␍`  prettier/prettier
  Line 197:10:   Delete `␍`  prettier/prettier
  Line 198:57:   Delete `␍`  prettier/prettier
  Line 199:37:   Delete `␍`  prettier/prettier
  Line 200:41:   Delete `␍`  prettier/prettier
  Line 201:30:   Delete `␍`  prettier/prettier
  Line 202:19:   Delete `␍`  prettier/prettier
  Line 203:34:   Delete `␍`  prettier/prettier
  Line 204:44:   Delete `␍`  prettier/prettier
  Line 205:66:   Delete `␍`  prettier/prettier
  Line 206:18:   Delete `␍`  prettier/prettier
  Line 207:23:   Delete `␍`  prettier/prettier
  Line 208:26:   Delete `␍`  prettier/prettier
  Line 209:78:   Delete `␍`  prettier/prettier
  Line 210:22:   Delete `␍`  prettier/prettier
  Line 211:29:   Delete `␍`  prettier/prettier
  Line 212:37:   Delete `␍`  prettier/prettier
  Line 213:41:   Delete `␍`  prettier/prettier
  Line 214:68:   Delete `␍`  prettier/prettier
  Line 215:50:   Delete `␍`  prettier/prettier
  Line 216:22:   Delete `␍`  prettier/prettier
  Line 217:29:   Delete `␍`  prettier/prettier
  Line 218:37:   Delete `␍`  prettier/prettier
  Line 219:41:   Delete `␍`  prettier/prettier
  Line 220:60:   Delete `␍`  prettier/prettier
  Line 221:55:   Delete `␍`  prettier/prettier
  Line 222:22:   Delete `␍`  prettier/prettier
  Line 223:29:   Delete `␍`  prettier/prettier
  Line 224:22:   Delete `␍`  prettier/prettier
  Line 225:16:   Delete `␍`  prettier/prettier
  Line 226:13:   Delete `␍`  prettier/prettier
  Line 227:11:   Delete `␍`  prettier/prettier
  Line 228:5:    Delete `␍`  prettier/prettier
  Line 229:2:    Delete `␍`  prettier/prettier

src\components\Ramper.jsx
  Line 1:52:   Delete `␍`  prettier/prettier
  Line 2:44:   Delete `␍`  prettier/prettier
  Line 3:1:    Delete `␍`  prettier/prettier
  Line 4:20:   Delete `␍`  prettier/prettier
  Line 5:42:   Delete `␍`  prettier/prettier
  Line 6:36:   Delete `␍`  prettier/prettier
  Line 7:20:   Delete `␍`  prettier/prettier
  Line 8:54:   Delete `␍`  prettier/prettier
  Line 9:34:   Delete `␍`  prettier/prettier
  Line 10:27:  Delete `␍`  prettier/prettier
  Line 11:44:  Delete `␍`  prettier/prettier
  Line 12:47:  Delete `␍`  prettier/prettier
  Line 13:6:   Delete `␍`  prettier/prettier
  Line 14:18:  Delete `␍`  prettier/prettier
  Line 15:60:  Delete `␍`  prettier/prettier
  Line 16:25:  Delete `␍`  prettier/prettier
  Line 17:1:   Delete `␍`  prettier/prettier
  Line 18:11:  Delete `␍`  prettier/prettier
  Line 19:12:  Delete `␍`  prettier/prettier
  Line 20:19:  Delete `␍`  prettier/prettier
  Line 21:21:  Delete `␍`  prettier/prettier
  Line 22:23:  Delete `␍`  prettier/prettier
  Line 23:67:  Delete `␍`  prettier/prettier
  Line 24:15:  Delete `␍`  prettier/prettier
  Line 25:24:  Delete `␍`  prettier/prettier
  Line 26:25:  Delete `␍`  prettier/prettier
  Line 27:61:  Delete `␍`  prettier/prettier
  Line 28:37:  Delete `␍`  prettier/prettier
  Line 29:30:  Delete `␍`  prettier/prettier
  Line 30:34:  Delete `␍`  prettier/prettier
  Line 31:9:   Delete `␍`  prettier/prettier
  Line 32:7:   Delete `␍`  prettier/prettier
  Line 33:5:   Delete `␍`  prettier/prettier
  Line 34:2:   Delete `␍`  prettier/prettier
  Line 35:1:   Delete `␍`  prettier/prettier
  Line 36:23:  Delete `␍`  prettier/prettier

src\components\TokenPrice.jsx
  Line 1:34:   Delete `␍`  prettier/prettier
  Line 2:47:   Delete `␍`  prettier/prettier
  Line 3:1:    Delete `␍`  prettier/prettier
  Line 4:17:   Delete `␍`  prettier/prettier
  Line 5:11:   Delete `␍`  prettier/prettier
  Line 6:22:   Delete `␍`  prettier/prettier
  Line 7:20:   Delete `␍`  prettier/prettier
  Line 8:16:   Delete `␍`  prettier/prettier
  Line 9:26:   Delete `␍`  prettier/prettier
  Line 10:21:  Delete `␍`  prettier/prettier
  Line 11:30:  Delete `␍`  prettier/prettier
  Line 12:26:  Delete `␍`  prettier/prettier
  Line 13:26:  Delete `␍`  prettier/prettier
  Line 14:5:   Delete `␍`  prettier/prettier
  Line 15:3:   Delete `␍`  prettier/prettier
  Line 16:29:  Delete `␍`  prettier/prettier
  Line 17:56:  Delete `␍`  prettier/prettier
  Line 18:1:   Delete `␍`  prettier/prettier
  Line 19:52:  Delete `␍`  prettier/prettier
  Line 20:1:   Delete `␍`  prettier/prettier
  Line 21:61:  Delete `␍`  prettier/prettier
  Line 22:1:   Delete `␍`  prettier/prettier
  Line 23:74:  Delete `␍`  prettier/prettier
  Line 24:1:   Delete `␍`  prettier/prettier
  Line 25:11:  Delete `␍`  prettier/prettier
  Line 26:31:  Delete `␍`  prettier/prettier
  Line 27:11:  Delete `␍`  prettier/prettier
  Line 28:41:  Delete `␍`  prettier/prettier
  Line 29:19:  Delete `␍`  prettier/prettier
  Line 30:50:  Delete `␍`  prettier/prettier
  Line 31:9:   Delete `␍`  prettier/prettier
  Line 32:12:  Delete `␍`  prettier/prettier
  Line 33:38:  Delete `␍`  prettier/prettier
  Line 34:37:  Delete `␍`  prettier/prettier
  Line 35:55:  Delete `␍`  prettier/prettier
  Line 36:8:   Delete `␍`  prettier/prettier
  Line 37:26:  Delete `␍`  prettier/prettier
  Line 38:21:  Delete `␍`  prettier/prettier
  Line 39:41:  Delete `␍`  prettier/prettier
  Line 40:46:  Delete `␍`  prettier/prettier
  Line 41:14:  Delete `␍`  prettier/prettier
  Line 42:11:  Delete `␍`  prettier/prettier
  Line 43:5:   Delete `␍`  prettier/prettier
  Line 44:2:   Delete `␍`  prettier/prettier
  Line 45:27:  Delete `␍`  prettier/prettier

src\components\Wallet\Wallet.jsx
  Line 1:46:   Delete `␍`  prettier/prettier
  Line 2:46:   Delete `␍`  prettier/prettier
  Line 3:42:   Delete `␍`  prettier/prettier
  Line 4:34:   Delete `␍`  prettier/prettier
  Line 5:29:   Delete `␍`  prettier/prettier
  Line 6:1:    Delete `␍`  prettier/prettier
  Line 7:17:   Delete `␍`  prettier/prettier
  Line 8:11:   Delete `␍`  prettier/prettier
  Line 9:22:   Delete `␍`  prettier/prettier
  Line 10:23:  Delete `␍`  prettier/prettier
  Line 11:5:   Delete `␍`  prettier/prettier
  Line 12:12:  Delete `␍`  prettier/prettier
  Line 13:21:  Delete `␍`  prettier/prettier
  Line 14:29:  Delete `␍`  prettier/prettier
  Line 15:26:  Delete `␍`  prettier/prettier
  Line 16:16:  Delete `␍`  prettier/prettier
  Line 17:5:   Delete `␍`  prettier/prettier
  Line 18:10:  Delete `␍`  prettier/prettier
  Line 19:57:  Delete `␍`  prettier/prettier
  Line 20:33:  Delete `␍`  prettier/prettier
  Line 21:26:  Delete `␍`  prettier/prettier
  Line 22:20:  Delete `␍`  prettier/prettier
  Line 23:22:  Delete `␍`  prettier/prettier
  Line 24:23:  Delete `␍`  prettier/prettier
  Line 25:5:   Delete `␍`  prettier/prettier
  Line 26:3:   Delete `␍`  prettier/prettier
  Line 27:1:   Delete `␍`  prettier/prettier
  Line 28:20:  Delete `␍`  prettier/prettier
  Line 29:11:  Delete `␍`  prettier/prettier
  Line 30:10:  Delete `␍`  prettier/prettier
  Line 31:26:  Delete `␍`  prettier/prettier
  Line 32:14:  Delete `␍`  prettier/prettier
  Line 33:36:  Delete `␍`  prettier/prettier
  Line 34:59:  Delete `␍`  prettier/prettier
  Line 35:40:  Delete `␍`  prettier/prettier
  Line 36:28:  Delete `␍`  prettier/prettier
  Line 37:15:  Delete `␍`  prettier/prettier
  Line 38:8:   Delete `␍`  prettier/prettier
  Line 39:6:   Delete `␍`  prettier/prettier
  Line 40:19:  Delete `␍`  prettier/prettier
  Line 41:12:  Delete `␍`  prettier/prettier
  Line 42:5:   Delete `␍`  prettier/prettier
  Line 43:2:   Delete `␍`  prettier/prettier
  Line 44:1:   Delete `␍`  prettier/prettier
  Line 45:23:  Delete `␍`  prettier/prettier

src\components\Wallet\components\AssetSelector.jsx
  Line 1:57:   Delete `␍`  prettier/prettier
  Line 2:62:   Delete `␍`  prettier/prettier
  Line 3:38:   Delete `␍`  prettier/prettier
  Line 4:33:   Delete `␍`  prettier/prettier
  Line 5:1:    Delete `␍`  prettier/prettier
  Line 6:61:   Delete `␍`  prettier/prettier
  Line 7:40:   Delete `␍`  prettier/prettier
  Line 8:67:   Delete `␍`  prettier/prettier
  Line 9:36:   Delete `␍`  prettier/prettier
  Line 10:1:   Delete `␍`  prettier/prettier
  Line 11:38:  Delete `␍`  prettier/prettier
  Line 12:48:  Delete `␍`  prettier/prettier
  Line 13:13:  Delete `␍`  prettier/prettier
  Line 14:17:  Delete `␍`  prettier/prettier
  Line 15:8:   Delete `␍`  prettier/prettier
  Line 16:40:  Delete `␍`  prettier/prettier
  Line 17:40:  Delete `␍`  prettier/prettier
  Line 18:32:  Delete `␍`  prettier/prettier
  Line 19:36:  Delete `␍`  prettier/prettier
  Line 20:69:  Delete `␍`  prettier/prettier
  Line 21:9:   Delete `␍`  prettier/prettier
  Line 22:7:   Delete `␍`  prettier/prettier
  Line 23:44:  Delete `␍`  prettier/prettier
  Line 24:1:   Delete `␍`  prettier/prettier
  Line 25:33:  Delete `␍`  prettier/prettier
  Line 26:78:  Delete `␍`  prettier/prettier
  Line 27:21:  Delete `␍`  prettier/prettier
  Line 28:4:   Delete `␍`  prettier/prettier
  Line 29:1:   Delete `␍`  prettier/prettier
  Line 30:11:  Delete `␍`  prettier/prettier
  Line 31:64:  Delete `␍`  prettier/prettier
  Line 32:22:  Delete `␍`  prettier/prettier
  Line 33:36:  Delete `␍`  prettier/prettier
  Line 34:29:  Delete `␍`  prettier/prettier
  Line 35:19:  Delete `␍`  prettier/prettier
  Line 36:27:  Delete `␍`  prettier/prettier
  Line 37:44:  Delete `␍`  prettier/prettier
  Line 38:42:  Delete `␍`  prettier/prettier
  Line 39:14:  Delete `␍`  prettier/prettier
  Line 40:19:  Delete `␍`  prettier/prettier
  Line 41:25:  Delete `␍`  prettier/prettier
  Line 42:35:  Delete `␍`  prettier/prettier
  Line 43:40:  Delete `␍`  prettier/prettier
  Line 44:33:  Delete `␍`  prettier/prettier
  Line 45:30:  Delete `␍`  prettier/prettier
  Line 46:19:  Delete `␍`  prettier/prettier
  Line 47:16:  Delete `␍`  prettier/prettier
  Line 48:23:  Delete `␍`  prettier/prettier
  Line 49:24:  Delete `␍`  prettier/prettier
  Line 50:33:  Delete `␍`  prettier/prettier
  Line 51:71:  Delete `␍`  prettier/prettier
  Line 52:20:  Delete `␍`  prettier/prettier
  Line 53:31:  Delete `␍`  prettier/prettier
  Line 54:31:  Delete `␍`  prettier/prettier
  Line 55:32:  Delete `␍`  prettier/prettier
  Line 56:34:  Delete `␍`  prettier/prettier
  Line 57:51:  Delete `␍`  prettier/prettier
  Line 58:19:  Delete `␍`  prettier/prettier
  Line 59:21:  Delete `␍`  prettier/prettier
  Line 60:27:  Delete `␍`  prettier/prettier
  Line 61:37:  Delete `␍`  prettier/prettier
  Line 62:53:  Delete `␍`  prettier/prettier
  Line 63:34:  Delete `␍`  prettier/prettier
  Line 64:21:  Delete `␍`  prettier/prettier
  Line 65:18:  Delete `␍`  prettier/prettier
  Line 66:39:  Delete `␍`  prettier/prettier
  Line 67:53:  Delete `␍`  prettier/prettier
  Line 68:22:  Delete `␍`  prettier/prettier
  Line 69:33:  Delete `␍`  prettier/prettier
  Line 70:76:  Delete `␍`  prettier/prettier
  Line 71:35:  Delete `␍`  prettier/prettier
  Line 72:22:  Delete `␍`  prettier/prettier
  Line 73:23:  Delete `␍`  prettier/prettier
  Line 74:23:  Delete `␍`  prettier/prettier
  Line 75:21:  Delete `␍`  prettier/prettier
  Line 76:29:  Delete `␍`  prettier/prettier
  Line 77:13:  Delete `␍`  prettier/prettier
  Line 78:12:  Delete `␍`  prettier/prettier
  Line 79:14:  Delete `␍`  prettier/prettier
  Line 80:5:   Delete `␍`  prettier/prettier
  Line 81:2:   Delete `␍`  prettier/prettier

src\components\Wallet\components\Transfer.jsx
  Line 1:56:    Delete `␍`  prettier/prettier
  Line 2:52:    Delete `␍`  prettier/prettier
  Line 3:45:    Delete `␍`  prettier/prettier
  Line 4:45:    Delete `␍`  prettier/prettier
  Line 5:44:    Delete `␍`  prettier/prettier
  Line 6:47:    Delete `␍`  prettier/prettier
  Line 7:45:    Delete `␍`  prettier/prettier
  Line 8:1:     Delete `␍`  prettier/prettier
  Line 9:17:    Delete `␍`  prettier/prettier
  Line 10:10:   Delete `␍`  prettier/prettier
  Line 11:26:   Delete `␍`  prettier/prettier
  Line 12:19:   Delete `␍`  prettier/prettier
  Line 13:5:    Delete `␍`  prettier/prettier
  Line 14:12:   Delete `␍`  prettier/prettier
  Line 15:25:   Delete `␍`  prettier/prettier
  Line 16:5:    Delete `␍`  prettier/prettier
  Line 17:11:   Delete `␍`  prettier/prettier
  Line 18:19:   Delete `␍`  prettier/prettier
  Line 19:21:   Delete `␍`  prettier/prettier
  Line 20:22:   Delete `␍`  prettier/prettier
  Line 21:26:   Delete `␍`  prettier/prettier
  Line 22:24:   Delete `␍`  prettier/prettier
  Line 23:29:   Delete `␍`  prettier/prettier
  Line 24:29:   Delete `␍`  prettier/prettier
  Line 25:22:   Delete `␍`  prettier/prettier
  Line 26:23:   Delete `␍`  prettier/prettier
  Line 27:20:   Delete `␍`  prettier/prettier
  Line 28:36:   Delete `␍`  prettier/prettier
  Line 29:5:    Delete `␍`  prettier/prettier
  Line 30:12:   Delete `␍`  prettier/prettier
  Line 31:23:   Delete `␍`  prettier/prettier
  Line 32:21:   Delete `␍`  prettier/prettier
  Line 33:26:   Delete `␍`  prettier/prettier
  Line 34:5:    Delete `␍`  prettier/prettier
  Line 35:52:   Delete `␍`  prettier/prettier
  Line 36:9:    Delete `␍`  prettier/prettier
  Line 37:21:   Delete `␍`  prettier/prettier
  Line 38:26:   Delete `␍`  prettier/prettier
  Line 39:17:   Delete `␍`  prettier/prettier
  Line 40:26:   Delete `␍`  prettier/prettier
  Line 41:5:    Delete `␍`  prettier/prettier
  Line 42:3:    Delete `␍`  prettier/prettier
  Line 43:1:    Delete `␍`  prettier/prettier
  Line 44:22:   Delete `␍`  prettier/prettier
  Line 45:36:   Delete `␍`  prettier/prettier
  Line 46:46:   Delete `␍`  prettier/prettier
  Line 47:40:   Delete `␍`  prettier/prettier
  Line 48:34:   Delete `␍`  prettier/prettier
  Line 49:42:   Delete `␍`  prettier/prettier
  Line 50:53:   Delete `␍`  prettier/prettier
  Line 51:1:    Delete `␍`  prettier/prettier
  Line 52:20:   Delete `␍`  prettier/prettier
  Line 53:80:   Delete `␍`  prettier/prettier
  Line 54:33:   Delete `␍`  prettier/prettier
  Line 55:1:    Delete `␍`  prettier/prettier
  Line 56:59:   Delete `␍`  prettier/prettier
  Line 57:24:   Delete `␍`  prettier/prettier
  Line 58:32:   Delete `␍`  prettier/prettier
  Line 59:15:   Delete `␍`  prettier/prettier
  Line 60:19:   Delete `␍`  prettier/prettier
  Line 61:23:   Delete `␍`  prettier/prettier
  Line 62:46:   Delete `␍`  prettier/prettier
  Line 63:9:    Delete `␍`  prettier/prettier
  Line 64:8:    Delete `␍`  prettier/prettier
  Line 65:5:    Delete `␍`  prettier/prettier
  Line 66:1:    Delete `␍`  prettier/prettier
  Line 67:30:   Delete `␍`  prettier/prettier
  Line 68:44:   Delete `␍`  prettier/prettier
  Line 69:1:    Delete `␍`  prettier/prettier
  Line 70:22:   Delete `␍`  prettier/prettier
  Line 71:1:    Delete `␍`  prettier/prettier
  Line 72:35:   Delete `␍`  prettier/prettier
  Line 73:57:   Delete `␍`  prettier/prettier
  Line 74:20:   Delete `␍`  prettier/prettier
  Line 75:28:   Delete `␍`  prettier/prettier
  Line 76:45:   Delete `␍`  prettier/prettier
  Line 77:20:   Delete `␍`  prettier/prettier
  Line 78:31:   Delete `␍`  prettier/prettier
  Line 79:11:   Delete `␍`  prettier/prettier
  Line 80:15:   Delete `␍`  prettier/prettier
  Line 81:15:   Delete `␍`  prettier/prettier
  Line 82:20:   Delete `␍`  prettier/prettier
  Line 83:25:   Delete `␍`  prettier/prettier
  Line 84:63:   Delete `␍`  prettier/prettier
  Line 85:20:   Delete `␍`  prettier/prettier
  Line 86:48:   Delete `␍`  prettier/prettier
  Line 87:31:   Delete `␍`  prettier/prettier
  Line 88:11:   Delete `␍`  prettier/prettier
  Line 89:6:    Delete `␍`  prettier/prettier
  Line 90:1:    Delete `␍`  prettier/prettier
  Line 91:24:   Delete `␍`  prettier/prettier
  Line 92:54:   Delete `␍`  prettier/prettier
  Line 93:1:    Delete `␍`  prettier/prettier
  Line 94:13:   Delete `␍`  prettier/prettier
  Line 95:41:   Delete `␍`  prettier/prettier
  Line 96:27:   Delete `␍`  prettier/prettier
  Line 97:41:   Delete `␍`  prettier/prettier
  Line 98:34:   Delete `␍`  prettier/prettier
  Line 99:12:   Delete `␍`  prettier/prettier
  Line 100:49:  Delete `␍`  prettier/prettier
  Line 101:9:   Delete `␍`  prettier/prettier
  Line 102:36:  Delete `␍`  prettier/prettier
  Line 103:27:  Delete `␍`  prettier/prettier
  Line 104:37:  Delete `␍`  prettier/prettier
  Line 105:53:  Delete `␍`  prettier/prettier
  Line 106:12:  Delete `␍`  prettier/prettier
  Line 107:50:  Delete `␍`  prettier/prettier
  Line 108:29:  Delete `␍`  prettier/prettier
  Line 109:9:   Delete `␍`  prettier/prettier
  Line 110:32:  Delete `␍`  prettier/prettier
  Line 111:27:  Delete `␍`  prettier/prettier
  Line 112:31:  Delete `␍`  prettier/prettier
  Line 113:43:  Delete `␍`  prettier/prettier
  Line 114:12:  Delete `␍`  prettier/prettier
  Line 115:30:  Delete `␍`  prettier/prettier
  Line 116:29:  Delete `␍`  prettier/prettier
  Line 117:10:  Delete `␍`  prettier/prettier
  Line 118:4:   Delete `␍`  prettier/prettier
  Line 119:1:   Delete `␍`  prettier/prettier
  Line 120:11:  Delete `␍`  prettier/prettier
  Line 121:30:  Delete `␍`  prettier/prettier
  Line 122:35:  Delete `␍`  prettier/prettier
  Line 123:36:  Delete `␍`  prettier/prettier
  Line 124:35:  Delete `␍`  prettier/prettier
  Line 125:15:  Delete `␍`  prettier/prettier
  Line 126:36:  Delete `␍`  prettier/prettier
  Line 127:43:  Delete `␍`  prettier/prettier
  Line 128:41:  Delete `␍`  prettier/prettier
  Line 129:17:  Delete `␍`  prettier/prettier
  Line 130:60:  Delete `␍`  prettier/prettier
  Line 131:15:  Delete `␍`  prettier/prettier
  Line 132:36:  Delete `␍`  prettier/prettier
  Line 133:43:  Delete `␍`  prettier/prettier
  Line 134:40:  Delete `␍`  prettier/prettier
  Line 135:17:  Delete `␍`  prettier/prettier
  Line 136:17:  Delete `␍`  prettier/prettier
  Line 137:25:  Delete `␍`  prettier/prettier
  Line 138:44:  Delete `␍`  prettier/prettier
  Line 139:31:  Delete `␍`  prettier/prettier
  Line 140:46:  Delete `␍`  prettier/prettier
  Line 141:15:  Delete `␍`  prettier/prettier
  Line 142:13:  Delete `␍`  prettier/prettier
  Line 143:15:  Delete `␍`  prettier/prettier
  Line 144:36:  Delete `␍`  prettier/prettier
  Line 145:43:  Delete `␍`  prettier/prettier
  Line 146:39:  Delete `␍`  prettier/prettier
  Line 147:17:  Delete `␍`  prettier/prettier
  Line 148:74:  Delete `␍`  prettier/prettier
  Line 149:15:  Delete `␍`  prettier/prettier
  Line 150:16:  Delete `␍`  prettier/prettier
  Line 151:25:  Delete `␍`  prettier/prettier
  Line 152:23:  Delete `␍`  prettier/prettier
  Line 153:30:  Delete `␍`  prettier/prettier
  Line 154:55:  Delete `␍`  prettier/prettier
  Line 155:37:  Delete `␍`  prettier/prettier
  Line 156:25:  Delete `␍`  prettier/prettier
  Line 157:10:  Delete `␍`  prettier/prettier
  Line 158:21:  Delete `␍`  prettier/prettier
  Line 159:18:  Delete `␍`  prettier/prettier
  Line 160:13:  Delete `␍`  prettier/prettier
  Line 161:11:  Delete `␍`  prettier/prettier
  Line 162:5:   Delete `␍`  prettier/prettier
  Line 163:2:   Delete `␍`  prettier/prettier
  Line 164:1:   Delete `␍`  prettier/prettier
  Line 165:25:  Delete `␍`  prettier/prettier

src\components\Wallet\index.js
  Line 1:36:  Delete `␍`  prettier/prettier

src\helpers\formatters.js
  Line 1:51:   Delete `␍`  prettier/prettier
  Line 2:20:   Delete `␍`  prettier/prettier
  Line 3:28:   Delete `␍`  prettier/prettier
  Line 4:28:   Delete `␍`  prettier/prettier
  Line 5:4:    Delete `␍`  prettier/prettier
  Line 6:51:   Delete `␍`  prettier/prettier
  Line 7:20:   Delete `␍`  prettier/prettier
  Line 8:28:   Delete `␍`  prettier/prettier
  Line 9:28:   Delete `␍`  prettier/prettier
  Line 10:4:   Delete `␍`  prettier/prettier
  Line 11:1:   Delete `␍`  prettier/prettier
  Line 12:51:  Delete `␍`  prettier/prettier
  Line 13:21:  Delete `␍`  prettier/prettier
  Line 14:19:  Delete `␍`  prettier/prettier
  Line 15:28:  Delete `␍`  prettier/prettier
  Line 16:28:  Delete `␍`  prettier/prettier
  Line 17:4:   Delete `␍`  prettier/prettier
  Line 18:1:   Delete `␍`  prettier/prettier
  Line 19:4:   Delete `␍`  prettier/prettier
  Line 20:40:  Delete `␍`  prettier/prettier
  Line 21:40:  Delete `␍`  prettier/prettier
  Line 22:58:  Delete `␍`  prettier/prettier
  Line 23:21:  Delete `␍`  prettier/prettier
  Line 24:4:   Delete `␍`  prettier/prettier
  Line 25:48:  Delete `␍`  prettier/prettier
  Line 26:13:  Delete `␍`  prettier/prettier
  Line 27:64:  Delete `␍`  prettier/prettier
  Line 28:4:   Delete `␍`  prettier/prettier
  Line 29:13:  Delete `␍`  prettier/prettier
  Line 30:3:   Delete `␍`  prettier/prettier
  Line 31:1:   Delete `␍`  prettier/prettier
  Line 32:47:  Delete `␍`  prettier/prettier
  Line 33:53:  Delete `␍`  prettier/prettier
  Line 34:1:   Delete `␍`  prettier/prettier
  Line 35:4:   Delete `␍`  prettier/prettier
  Line 36:56:  Delete `␍`  prettier/prettier
  Line 37:39:  Delete `␍`  prettier/prettier
  Line 38:47:  Delete `␍`  prettier/prettier
  Line 39:39:  Delete `␍`  prettier/prettier
  Line 40:21:  Delete `␍`  prettier/prettier
  Line 41:4:   Delete `␍`  prettier/prettier
  Line 42:58:  Delete `␍`  prettier/prettier
  Line 43:57:  Delete `␍`  prettier/prettier

src\helpers\networks.js
  Line 1:32:   Delete `␍`  prettier/prettier
  Line 2:11:   Delete `␍`  prettier/prettier
  Line 3:27:   Delete `␍`  prettier/prettier
  Line 4:47:   Delete `␍`  prettier/prettier
  Line 5:59:   Delete `␍`  prettier/prettier
  Line 6:5:    Delete `␍`  prettier/prettier
  Line 7:11:   Delete `␍`  prettier/prettier
  Line 8:27:   Delete `␍`  prettier/prettier
  Line 9:55:   Delete `␍`  prettier/prettier
  Line 10:5:   Delete `␍`  prettier/prettier
  Line 11:11:  Delete `␍`  prettier/prettier
  Line 12:27:  Delete `␍`  prettier/prettier
  Line 13:53:  Delete `␍`  prettier/prettier
  Line 14:5:   Delete `␍`  prettier/prettier
  Line 15:12:  Delete `␍`  prettier/prettier
  Line 16:27:  Delete `␍`  prettier/prettier
  Line 17:55:  Delete `␍`  prettier/prettier
  Line 18:5:   Delete `␍`  prettier/prettier
  Line 19:11:  Delete `␍`  prettier/prettier
  Line 20:27:  Delete `␍`  prettier/prettier
  Line 21:54:  Delete `␍`  prettier/prettier
  Line 22:5:   Delete `␍`  prettier/prettier
  Line 23:13:  Delete `␍`  prettier/prettier
  Line 24:30:  Delete `␍`  prettier/prettier
  Line 25:25:  Delete `␍`  prettier/prettier
  Line 26:27:  Delete `␍`  prettier/prettier
  Line 27:37:  Delete `␍`  prettier/prettier
  Line 28:5:   Delete `␍`  prettier/prettier
  Line 29:14:  Delete `␍`  prettier/prettier
  Line 30:20:  Delete `␍`  prettier/prettier
  Line 31:36:  Delete `␍`  prettier/prettier
  Line 32:26:  Delete `␍`  prettier/prettier
  Line 33:28:  Delete `␍`  prettier/prettier
  Line 34:53:  Delete `␍`  prettier/prettier
  Line 35:63:  Delete `␍`  prettier/prettier
  Line 36:5:   Delete `␍`  prettier/prettier
  Line 37:12:  Delete `␍`  prettier/prettier
  Line 38:17:  Delete `␍`  prettier/prettier
  Line 39:30:  Delete `␍`  prettier/prettier
  Line 40:25:  Delete `␍`  prettier/prettier
  Line 41:27:  Delete `␍`  prettier/prettier
  Line 42:49:  Delete `␍`  prettier/prettier
  Line 43:46:  Delete `␍`  prettier/prettier
  Line 44:59:  Delete `␍`  prettier/prettier
  Line 45:5:   Delete `␍`  prettier/prettier
  Line 46:12:  Delete `␍`  prettier/prettier
  Line 47:17:  Delete `␍`  prettier/prettier
  Line 48:40:  Delete `␍`  prettier/prettier
  Line 49:25:  Delete `␍`  prettier/prettier
  Line 50:27:  Delete `␍`  prettier/prettier
  Line 51:63:  Delete `␍`  prettier/prettier
  Line 52:54:  Delete `␍`  prettier/prettier
  Line 53:5:   Delete `␍`  prettier/prettier
  Line 54:12:  Delete `␍`  prettier/prettier
  Line 55:18:  Delete `␍`  prettier/prettier
  Line 56:34:  Delete `␍`  prettier/prettier
  Line 57:27:  Delete `␍`  prettier/prettier
  Line 58:29:  Delete `␍`  prettier/prettier
  Line 59:51:  Delete `␍`  prettier/prettier
  Line 60:66:  Delete `␍`  prettier/prettier
  Line 61:59:  Delete `␍`  prettier/prettier
  Line 62:5:   Delete `␍`  prettier/prettier
  Line 63:15:  Delete `␍`  prettier/prettier
  Line 64:20:  Delete `␍`  prettier/prettier
  Line 65:25:  Delete `␍`  prettier/prettier
  Line 66:27:  Delete `␍`  prettier/prettier
  Line 67:29:  Delete `␍`  prettier/prettier
  Line 68:47:  Delete `␍`  prettier/prettier
  Line 69:57:  Delete `␍`  prettier/prettier
  Line 70:5:   Delete `␍`  prettier/prettier
  Line 71:3:   Delete `␍`  prettier/prettier
  Line 72:1:   Delete `␍`  prettier/prettier
  Line 73:43:  Delete `␍`  prettier/prettier
  Line 74:53:  Delete `␍`  prettier/prettier
  Line 75:1:   Delete `␍`  prettier/prettier
  Line 76:79:  Delete `␍`  prettier/prettier
  Line 77:1:   Delete `␍`  prettier/prettier
  Line 78:79:  Delete `␍`  prettier/prettier
  Line 79:1:   Delete `␍`  prettier/prettier
  Line 80:43:  Delete `␍`  prettier/prettier
  Line 81:42:  Delete `␍`  prettier/prettier

src\hooks\useERC20Balance.js
  Line 1:45:   Delete `␍`  prettier/prettier
  Line 2:63:   Delete `␍`  prettier/prettier
  Line 3:1:    Delete `␍`  prettier/prettier
  Line 4:45:   Delete `␍`  prettier/prettier
  Line 5:43:   Delete `␍`  prettier/prettier
  Line 6:75:   Delete `␍`  prettier/prettier
  Line 7:1:    Delete `␍`  prettier/prettier
  Line 8:42:   Delete `␍`  prettier/prettier
  Line 9:1:    Delete `␍`  prettier/prettier
  Line 10:20:  Delete `␍`  prettier/prettier
  Line 11:25:  Delete `␍`  prettier/prettier
  Line 12:65:  Delete `␍`  prettier/prettier
  Line 13:6:   Delete `␍`  prettier/prettier
  Line 14:60:  Delete `␍`  prettier/prettier
  Line 15:47:  Delete `␍`  prettier/prettier
  Line 16:1:   Delete `␍`  prettier/prettier
  Line 17:42:  Delete `␍`  prettier/prettier
  Line 18:25:  Delete `␍`  prettier/prettier
  Line 19:26:  Delete `␍`  prettier/prettier
  Line 20:32:  Delete `␍`  prettier/prettier
  Line 21:41:  Delete `␍`  prettier/prettier
  Line 22:9:   Delete `␍`  prettier/prettier
  Line 23:33:  Delete `␍`  prettier/prettier
  Line 24:5:   Delete `␍`  prettier/prettier
  Line 25:1:   Delete `␍`  prettier/prettier
  Line 26:40:  Delete `␍`  prettier/prettier
  Line 27:3:   Delete `␍`  prettier/prettier

src\hooks\useERC20Transfers.js
  Line 1:45:   Delete `␍`  prettier/prettier
  Line 2:63:   Delete `␍`  prettier/prettier
  Line 3:1:    Delete `␍`  prettier/prettier
  Line 4:41:   Delete `␍`  prettier/prettier
  Line 5:43:   Delete `␍`  prettier/prettier
  Line 6:75:   Delete `␍`  prettier/prettier
  Line 7:58:   Delete `␍`  prettier/prettier
  Line 8:1:    Delete `␍`  prettier/prettier
  Line 9:20:   Delete `␍`  prettier/prettier
  Line 10:23:  Delete `␍`  prettier/prettier
  Line 11:73:  Delete `␍`  prettier/prettier
  Line 12:60:  Delete `␍`  prettier/prettier
  Line 13:47:  Delete `␍`  prettier/prettier
  Line 14:1:   Delete `␍`  prettier/prettier
  Line 15:44:  Delete `␍`  prettier/prettier
  Line 16:25:  Delete `␍`  prettier/prettier
  Line 17:69:  Delete `␍`  prettier/prettier
  Line 18:40:  Delete `␍`  prettier/prettier
  Line 19:5:   Delete `␍`  prettier/prettier
  Line 20:59:  Delete `␍`  prettier/prettier
  Line 21:3:   Delete `␍`  prettier/prettier

src\hooks\useIPFS.js
  Line 1:31:  Delete `␍`  prettier/prettier
  Line 2:33:  Delete `␍`  prettier/prettier
  Line 3:54:  Delete `␍`  prettier/prettier
  Line 4:68:  Delete `␍`  prettier/prettier
  Line 5:5:   Delete `␍`  prettier/prettier
  Line 6:1:   Delete `␍`  prettier/prettier
  Line 7:26:  Delete `␍`  prettier/prettier
  Line 8:3:   Delete `␍`  prettier/prettier

src\hooks\useInchDex.js
  Line 1:45:   Delete `␍`  prettier/prettier
  Line 2:44:   Delete `␍`  prettier/prettier
  Line 3:1:    Delete `␍`  prettier/prettier
  Line 4:32:   Delete `␍`  prettier/prettier
  Line 5:45:   Delete `␍`  prettier/prettier
  Line 6:48:   Delete `␍`  prettier/prettier
  Line 7:1:    Delete `␍`  prettier/prettier
  Line 8:20:   Delete `␍`  prettier/prettier
  Line 9:57:   Delete `␍`  prettier/prettier
  Line 10:28:  Delete `␍`  prettier/prettier
  Line 11:37:  Delete `␍`  prettier/prettier
  Line 12:54:  Delete `␍`  prettier/prettier
  Line 13:41:  Delete `␍`  prettier/prettier
  Line 14:1:   Delete `␍`  prettier/prettier
  Line 15:37:  Delete `␍`  prettier/prettier
  Line 16:42:  Delete `␍`  prettier/prettier
  Line 17:80:  Delete `␍`  prettier/prettier
  Line 18:80:  Delete `␍`  prettier/prettier
  Line 19:79:  Delete `␍`  prettier/prettier
  Line 20:35:  Delete `␍`  prettier/prettier
  Line 21:27:  Delete `␍`  prettier/prettier
  Line 22:35:  Delete `␍`  prettier/prettier
  Line 23:20:  Delete `␍`  prettier/prettier
  Line 24:8:   Delete `␍`  prettier/prettier
  Line 25:1:   Delete `␍`  prettier/prettier
  Line 26:35:  Delete `␍`  prettier/prettier
  Line 27:53:  Delete `␍`  prettier/prettier
  Line 28:40:  Delete `␍`  prettier/prettier
  Line 29:18:  Delete `␍`  prettier/prettier
  Line 30:26:  Delete `␍`  prettier/prettier
  Line 31:18:  Delete `␍`  prettier/prettier
  Line 32:78:  Delete `␍`  prettier/prettier
  Line 33:36:  Delete `␍`  prettier/prettier
  Line 34:24:  Delete `␍`  prettier/prettier
  Line 35:69:  Delete `␍`  prettier/prettier
  Line 36:77:  Delete `␍`  prettier/prettier
  Line 37:55:  Delete `␍`  prettier/prettier
  Line 38:18:  Delete `␍`  prettier/prettier
  Line 39:11:  Delete `␍`  prettier/prettier
  Line 40:37:  Delete `␍`  prettier/prettier
  Line 41:34:  Delete `␍`  prettier/prettier
  Line 42:28:  Delete `␍`  prettier/prettier
  Line 43:52:  Delete `␍`  prettier/prettier
  Line 44:73:  Delete `␍`  prettier/prettier
  Line 45:77:  Delete `␍`  prettier/prettier
  Line 46:59:  Delete `␍`  prettier/prettier
  Line 47:16:  Delete `␍`  prettier/prettier
  Line 48:12:  Delete `␍`  prettier/prettier
  Line 49:11:  Delete `␍`  prettier/prettier
  Line 50:41:  Delete `␍`  prettier/prettier
  Line 51:6:   Delete `␍`  prettier/prettier
  Line 52:1:   Delete `␍`  prettier/prettier
  Line 53:25:  Delete `␍`  prettier/prettier
  Line 54:27:  Delete `␍`  prettier/prettier
  Line 55:42:  Delete `␍`  prettier/prettier
  Line 56:34:  Delete `␍`  prettier/prettier
  Line 57:10:  Delete `␍`  prettier/prettier
  Line 58:30:  Delete `␍`  prettier/prettier
  Line 59:9:   Delete `␍`  prettier/prettier
  Line 60:39:  Delete `␍`  prettier/prettier
  Line 61:4:   Delete `␍`  prettier/prettier
  Line 62:1:   Delete `␍`  prettier/prettier
  Line 63:34:  Delete `␍`  prettier/prettier
  Line 64:48:  Delete `␍`  prettier/prettier
  Line 65:79:  Delete `␍`  prettier/prettier
  Line 66:80:  Delete `␍`  prettier/prettier
  Line 67:79:  Delete `␍`  prettier/prettier
  Line 68:35:  Delete `␍`  prettier/prettier
  Line 69:27:  Delete `␍`  prettier/prettier
  Line 70:35:  Delete `␍`  prettier/prettier
  Line 71:20:  Delete `␍`  prettier/prettier
  Line 72:51:  Delete `␍`  prettier/prettier
  Line 73:19:  Delete `␍`  prettier/prettier
  Line 74:8:   Delete `␍`  prettier/prettier
  Line 75:4:   Delete `␍`  prettier/prettier
  Line 76:1:   Delete `␍`  prettier/prettier
  Line 77:43:  Delete `␍`  prettier/prettier
  Line 78:3:   Delete `␍`  prettier/prettier
  Line 79:1:   Delete `␍`  prettier/prettier
  Line 80:27:  Delete `␍`  prettier/prettier

src\hooks\useVerifyMetadata.js
  Line 1:34:    Delete `␍`  prettier/prettier
  Line 2:37:    Delete `␍`  prettier/prettier
  Line 3:1:     Delete `␍`  prettier/prettier
  Line 4:4:     Delete `␍`  prettier/prettier
  Line 5:78:    Delete `␍`  prettier/prettier
  Line 6:119:   Delete `␍`  prettier/prettier
  Line 7:75:    Delete `␍`  prettier/prettier
  Line 8:4:     Delete `␍`  prettier/prettier
  Line 9:41:    Delete `␍`  prettier/prettier
  Line 10:37:   Delete `␍`  prettier/prettier
  Line 11:46:   Delete `␍`  prettier/prettier
  Line 12:1:    Delete `␍`  prettier/prettier
  Line 13:6:    Delete `␍`  prettier/prettier
  Line 14:46:   Delete `␍`  prettier/prettier
  Line 15:25:   Delete `␍`  prettier/prettier
  Line 16:18:   Delete `␍`  prettier/prettier
  Line 17:6:    Delete `␍`  prettier/prettier
  Line 18:33:   Delete `␍`  prettier/prettier
  Line 19:47:   Delete `␍`  prettier/prettier
  Line 20:34:   Delete `␍`  prettier/prettier
  Line 21:23:   Delete `␍`  prettier/prettier
  Line 22:22:   Delete `␍`  prettier/prettier
  Line 23:31:   Delete `␍`  prettier/prettier
  Line 24:70:   Delete `␍`  prettier/prettier
  Line 25:23:   Delete `␍`  prettier/prettier
  Line 26:1:    Delete `␍`  prettier/prettier
  Line 27:6:    Delete `␍`  prettier/prettier
  Line 28:32:   Delete `␍`  prettier/prettier
  Line 29:31:   Delete `␍`  prettier/prettier
  Line 30:25:   Delete `␍`  prettier/prettier
  Line 31:19:   Delete `␍`  prettier/prettier
  Line 32:6:    Delete `␍`  prettier/prettier
  Line 33:36:   Delete `␍`  prettier/prettier
  Line 34:19:   Delete `␍`  prettier/prettier
  Line 35:60:   Delete `␍`  prettier/prettier
  Line 36:77:   Delete `␍`  prettier/prettier
  Line 37:14:   Delete `␍`  prettier/prettier
  Line 38:6:    Delete `␍`  prettier/prettier
  Line 39:19:   Delete `␍`  prettier/prettier
  Line 40:25:   Delete `␍`  prettier/prettier
  Line 41:33:   Delete `␍`  prettier/prettier
  Line 42:28:   Delete `␍`  prettier/prettier
  Line 43:25:   Delete `␍`  prettier/prettier
  Line 44:16:   Delete `␍`  prettier/prettier
  Line 45:25:   Delete `␍`  prettier/prettier
  Line 46:73:   Delete `␍`  prettier/prettier
  Line 47:41:   Delete `␍`  prettier/prettier
  Line 48:13:   Delete `␍`  prettier/prettier
  Line 49:10:   Delete `␍`  prettier/prettier
  Line 50:26:   Delete `␍`  prettier/prettier
  Line 51:18:   Delete `␍`  prettier/prettier
  Line 52:30:   Delete `␍`  prettier/prettier
  Line 53:60:   Delete `␍`  prettier/prettier
  Line 54:12:   Delete `␍`  prettier/prettier
  Line 55:16:   Delete `␍`  prettier/prettier
  Line 56:24:   Delete `␍`  prettier/prettier
  Line 57:64:   Delete `␍`  prettier/prettier
  Line 58:30:   Delete `␍`  prettier/prettier
  Line 59:36:   Delete `␍`  prettier/prettier
  Line 60:35:   Delete `␍`  prettier/prettier
  Line 61:13:   Delete `␍`  prettier/prettier
  Line 62:38:   Delete `␍`  prettier/prettier
  Line 63:35:   Delete `␍`  prettier/prettier
  Line 64:30:   Delete `␍`  prettier/prettier
  Line 65:20:   Delete `␍`  prettier/prettier
  Line 66:96:   Delete `␍`  prettier/prettier
  Line 67:15:   Delete `␍`  prettier/prettier
  Line 68:22:   Delete `␍`  prettier/prettier
  Line 69:16:   Delete `␍`  prettier/prettier
  Line 70:38:   Delete `␍`  prettier/prettier
  Line 71:16:   Delete `␍`  prettier/prettier
  Line 72:23:   Delete `␍`  prettier/prettier
  Line 73:73:   Delete `␍`  prettier/prettier
  Line 74:26:   Delete `␍`  prettier/prettier
  Line 75:13:   Delete `␍`  prettier/prettier
  Line 76:25:   Delete `␍`  prettier/prettier
  Line 77:9:    Delete `␍`  prettier/prettier
  Line 78:24:   Delete `␍`  prettier/prettier
  Line 79:73:   Delete `␍`  prettier/prettier
  Line 80:15:   Delete `␍`  prettier/prettier
  Line 81:15:   Delete `␍`  prettier/prettier
  Line 82:30:   Delete `␍`  prettier/prettier
  Line 83:12:   Delete `␍`  prettier/prettier
  Line 84:10:   Delete `␍`  prettier/prettier
  Line 85:20:   Delete `␍`  prettier/prettier
  Line 86:1:    Delete `␍`  prettier/prettier
  Line 87:6:    Delete `␍`  prettier/prettier
  Line 88:23:   Delete `␍`  prettier/prettier
  Line 89:25:   Delete `␍`  prettier/prettier
  Line 90:30:   Delete `␍`  prettier/prettier
  Line 91:6:    Delete `␍`  prettier/prettier
  Line 92:40:   Delete `␍`  prettier/prettier
  Line 93:19:   Delete `␍`  prettier/prettier
  Line 94:29:   Delete `␍`  prettier/prettier
  Line 95:16:   Delete `␍`  prettier/prettier
  Line 96:66:   Delete `␍`  prettier/prettier
  Line 97:19:   Delete `␍`  prettier/prettier
  Line 98:45:   Delete `␍`  prettier/prettier
  Line 99:56:   Delete `␍`  prettier/prettier
  Line 100:20:  Delete `␍`  prettier/prettier
  Line 101:1:   Delete `␍`  prettier/prettier
  Line 102:29:  Delete `␍`  prettier/prettier
  Line 103:25:  Delete `␍`  prettier/prettier

src\index.js
  Line 1:43:   Delete `␍`  prettier/prettier
  Line 2:34:   Delete `␍`  prettier/prettier
  Line 3:25:   Delete `␍`  prettier/prettier
  Line 4:49:   Delete `␍`  prettier/prettier
  Line 5:22:   Delete `␍`  prettier/prettier
  Line 6:74:   Delete `␍`  prettier/prettier
  Line 7:48:   Delete `␍`  prettier/prettier
  Line 8:1:    Delete `␍`  prettier/prettier
  Line 9:57:   Delete `␍`  prettier/prettier
  Line 10:1:   Delete `␍`  prettier/prettier
  Line 11:61:  Delete `␍`  prettier/prettier
  Line 12:61:  Delete `␍`  prettier/prettier
  Line 13:1:   Delete `␍`  prettier/prettier
  Line 14:28:  Delete `␍`  prettier/prettier
  Line 15:60:  Delete `␍`  prettier/prettier
  Line 16:13:  Delete `␍`  prettier/prettier
  Line 17:30:  Delete `␍`  prettier/prettier
  Line 18:21:  Delete `␍`  prettier/prettier
  Line 19:88:  Delete `␍`  prettier/prettier
  Line 20:7:   Delete `␍`  prettier/prettier
  Line 21:20:  Delete `␍`  prettier/prettier
  Line 22:13:  Delete `␍`  prettier/prettier
  Line 23:62:  Delete `␍`  prettier/prettier
  Line 24:29:  Delete `␍`  prettier/prettier
  Line 25:25:  Delete `␍`  prettier/prettier
  Line 26:7:   Delete `␍`  prettier/prettier
  Line 27:9:   Delete `␍`  prettier/prettier
  Line 28:13:  Delete `␍`  prettier/prettier
  Line 29:66:  Delete `␍`  prettier/prettier
  Line 30:23:  Delete `␍`  prettier/prettier
  Line 31:13:  Delete `␍`  prettier/prettier
  Line 32:7:   Delete `␍`  prettier/prettier
  Line 33:4:   Delete `␍`  prettier/prettier
  Line 34:3:   Delete `␍`  prettier/prettier
  Line 35:1:   Delete `␍`  prettier/prettier
  Line 36:17:  Delete `␍`  prettier/prettier
  Line 37:15:  Delete `␍`  prettier/prettier
  Line 38:21:  Delete `␍`  prettier/prettier
  Line 39:17:  Delete `␍`  prettier/prettier
  Line 40:35:  Delete `␍`  prettier/prettier
  Line 41:3:   Delete `␍`  prettier/prettier
  Line 42:1:   Delete `␍`  prettier/prettier
  Line 43:72:  Delete `␍`  prettier/prettier
  Line 44:73:  Delete `␍`  prettier/prettier
  Line 45:58:  Delete `␍`  prettier/prettier
  Line 46:38:  Delete `␍`  prettier/prettier

src\serviceWorkerRegistration.js
  Line 1:60:    Delete `␍`  prettier/prettier
  Line 2:40:    Delete `␍`  prettier/prettier
  Line 3:1:     Delete `␍`  prettier/prettier
  Line 4:79:    Delete `␍`  prettier/prettier
  Line 5:79:    Delete `␍`  prettier/prettier
  Line 6:80:    Delete `␍`  prettier/prettier
  Line 7:76:    Delete `␍`  prettier/prettier
  Line 8:44:    Delete `␍`  prettier/prettier
  Line 9:1:     Delete `␍`  prettier/prettier
  Line 10:77:   Delete `␍`  prettier/prettier
  Line 11:37:   Delete `␍`  prettier/prettier
  Line 12:1:    Delete `␍`  prettier/prettier
  Line 13:29:   Delete `␍`  prettier/prettier
  Line 14:46:   Delete `␍`  prettier/prettier
  Line 15:44:   Delete `␍`  prettier/prettier
  Line 16:44:   Delete `␍`  prettier/prettier
  Line 17:54:   Delete `␍`  prettier/prettier
  Line 18:36:   Delete `␍`  prettier/prettier
  Line 19:64:   Delete `␍`  prettier/prettier
  Line 20:7:    Delete `␍`  prettier/prettier
  Line 21:3:    Delete `␍`  prettier/prettier
  Line 22:1:    Delete `␍`  prettier/prettier
  Line 23:35:   Delete `␍`  prettier/prettier
  Line 24:79:   Delete `␍`  prettier/prettier
  Line 25:73:   Delete `␍`  prettier/prettier
  Line 26:77:   Delete `␍`  prettier/prettier
  Line 27:55:   Delete `␍`  prettier/prettier
  Line 28:78:   Delete `␍`  prettier/prettier
  Line 29:80:   Delete `␍`  prettier/prettier
  Line 30:84:   Delete `␍`  prettier/prettier
  Line 31:14:   Delete `␍`  prettier/prettier
  Line 32:6:    Delete `␍`  prettier/prettier
  Line 33:1:    Delete `␍`  prettier/prettier
  Line 34:44:   Delete `␍`  prettier/prettier
  Line 35:67:   Delete `␍`  prettier/prettier
  Line 36:1:    Delete `␍`  prettier/prettier
  Line 37:25:   Delete `␍`  prettier/prettier
  Line 38:94:   Delete `␍`  prettier/prettier
  Line 39:48:   Delete `␍`  prettier/prettier
  Line 40:1:    Delete `␍`  prettier/prettier
  Line 41:80:   Delete `␍`  prettier/prettier
  Line 42:45:   Delete `␍`  prettier/prettier
  Line 43:51:   Delete `␍`  prettier/prettier
  Line 44:23:   Delete `␍`  prettier/prettier
  Line 45:71:   Delete `␍`  prettier/prettier
  Line 46:67:   Delete `␍`  prettier/prettier
  Line 47:13:   Delete `␍`  prettier/prettier
  Line 48:12:   Delete `␍`  prettier/prettier
  Line 49:15:   Delete `␍`  prettier/prettier
  Line 50:58:   Delete `␍`  prettier/prettier
  Line 51:40:   Delete `␍`  prettier/prettier
  Line 52:8:    Delete `␍`  prettier/prettier
  Line 53:8:    Delete `␍`  prettier/prettier
  Line 54:4:    Delete `␍`  prettier/prettier
  Line 55:2:    Delete `␍`  prettier/prettier
  Line 56:1:    Delete `␍`  prettier/prettier
  Line 57:42:   Delete `␍`  prettier/prettier
  Line 58:26:   Delete `␍`  prettier/prettier
  Line 59:21:   Delete `␍`  prettier/prettier
  Line 60:30:   Delete `␍`  prettier/prettier
  Line 61:43:   Delete `␍`  prettier/prettier
  Line 62:58:   Delete `␍`  prettier/prettier
  Line 63:40:   Delete `␍`  prettier/prettier
  Line 64:18:   Delete `␍`  prettier/prettier
  Line 65:10:   Delete `␍`  prettier/prettier
  Line 66:49:   Delete `␍`  prettier/prettier
  Line 67:56:   Delete `␍`  prettier/prettier
  Line 68:54:   Delete `␍`  prettier/prettier
  Line 69:80:   Delete `␍`  prettier/prettier
  Line 70:76:   Delete `␍`  prettier/prettier
  Line 71:59:   Delete `␍`  prettier/prettier
  Line 72:27:   Delete `␍`  prettier/prettier
  Line 73:72:   Delete `␍`  prettier/prettier
  Line 74:78:   Delete `␍`  prettier/prettier
  Line 75:17:   Delete `␍`  prettier/prettier
  Line 76:1:    Delete `␍`  prettier/prettier
  Line 77:34:   Delete `␍`  prettier/prettier
  Line 78:47:   Delete `␍`  prettier/prettier
  Line 79:47:   Delete `␍`  prettier/prettier
  Line 80:16:   Delete `␍`  prettier/prettier
  Line 81:21:   Delete `␍`  prettier/prettier
  Line 82:63:   Delete `␍`  prettier/prettier
  Line 83:52:   Delete `␍`  prettier/prettier
  Line 84:63:   Delete `␍`  prettier/prettier
  Line 85:65:   Delete `␍`  prettier/prettier
  Line 86:1:    Delete `␍`  prettier/prettier
  Line 87:34:   Delete `␍`  prettier/prettier
  Line 88:48:   Delete `␍`  prettier/prettier
  Line 89:48:   Delete `␍`  prettier/prettier
  Line 90:16:   Delete `␍`  prettier/prettier
  Line 91:14:   Delete `␍`  prettier/prettier
  Line 92:12:   Delete `␍`  prettier/prettier
  Line 93:11:   Delete `␍`  prettier/prettier
  Line 94:9:    Delete `␍`  prettier/prettier
  Line 95:7:    Delete `␍`  prettier/prettier
  Line 96:24:   Delete `␍`  prettier/prettier
  Line 97:73:   Delete `␍`  prettier/prettier
  Line 98:8:    Delete `␍`  prettier/prettier
  Line 99:2:    Delete `␍`  prettier/prettier
  Line 100:1:   Delete `␍`  prettier/prettier
  Line 101:50:  Delete `␍`  prettier/prettier
  Line 102:76:  Delete `␍`  prettier/prettier
  Line 103:17:  Delete `␍`  prettier/prettier
  Line 104:45:  Delete `␍`  prettier/prettier
  Line 105:5:   Delete `␍`  prettier/prettier
  Line 106:26:  Delete `␍`  prettier/prettier
  Line 107:81:  Delete `␍`  prettier/prettier
  Line 108:64:  Delete `␍`  prettier/prettier
  Line 109:11:  Delete `␍`  prettier/prettier
  Line 110:35:  Delete `␍`  prettier/prettier
  Line 111:74:  Delete `␍`  prettier/prettier
  Line 112:10:  Delete `␍`  prettier/prettier
  Line 113:79:  Delete `␍`  prettier/prettier
  Line 114:63:  Delete `␍`  prettier/prettier
  Line 115:49:  Delete `␍`  prettier/prettier
  Line 116:38:  Delete `␍`  prettier/prettier
  Line 117:14:  Delete `␍`  prettier/prettier
  Line 118:12:  Delete `␍`  prettier/prettier
  Line 119:15:  Delete `␍`  prettier/prettier
  Line 120:52:  Delete `␍`  prettier/prettier
  Line 121:40:  Delete `␍`  prettier/prettier
  Line 122:8:   Delete `␍`  prettier/prettier
  Line 123:7:   Delete `␍`  prettier/prettier
  Line 124:19:  Delete `␍`  prettier/prettier
  Line 125:19:  Delete `␍`  prettier/prettier
  Line 126:73:  Delete `␍`  prettier/prettier
  Line 127:9:   Delete `␍`  prettier/prettier
  Line 128:8:   Delete `␍`  prettier/prettier
  Line 129:2:   Delete `␍`  prettier/prettier
  Line 130:1:   Delete `␍`  prettier/prettier
  Line 131:31:  Delete `␍`  prettier/prettier
  Line 132:38:  Delete `␍`  prettier/prettier
  Line 133:34:  Delete `␍`  prettier/prettier
  Line 134:32:  Delete `␍`  prettier/prettier
  Line 135:35:  Delete `␍`  prettier/prettier
  Line 136:9:   Delete `␍`  prettier/prettier
  Line 137:26:  Delete `␍`  prettier/prettier
  Line 138:38:  Delete `␍`  prettier/prettier
  Line 139:10:  Delete `␍`  prettier/prettier
  Line 140:4:   Delete `␍`  prettier/prettier
  Line 141:2:   Delete `␍`  prettier/prettier

Search for the keywords to learn more about each error.

**Comment by piresg** [comment]
Hi,
This worked for me.
np
git config --global core.autocrlf false

then push the code again.
Regards

**Comment by Y0moo** [comment]
Should be fixed in the latest version. Check https://github.com/ethereum-boilerplate/ethereum-boilerplate/blob/main/.eslintrc#L33

**Comment by YosephKS** [comment]
@Shiba-Matic  try `yarn format` if you get such error

**Comment by 2kenyo** [comment]
open prettierignore and add this line of code `src/`

**Comment by brankozecevic** [comment]
> Should be fixed in the latest version. Check https://github.com/ethereum-boilerplate/ethereum-boilerplate/blob/main/.eslintrc#L33

I'm still getting this error after I make a change in code.
The best to do is probably:

git config --global core.autocrlf false

and

yarn format 

if you get this error after making change in code

**Comment by Y0moo** [comment]
Closing since we released V2
